### ISSUE TITLE
NameError: name 'IGNORE_TORCH_VER' is not defined

### ISSUE THREAD

**Issue by zhengbi-yong** [wrc042/TorchSDF#4]
`(dexgraspnet) X@X:~/DOWNLOAD/TorchSDF$ bash install.sh
Traceback (most recent call last):
  File "/home/X/DOWNLOAD/TorchSDF/setup.py", line 32, in <module>
    if IGNORE_TORCH_VER:
NameError: name 'IGNORE_TORCH_VER' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/X/DOWNLOAD/TorchSDF/torchsdf/__init__.py", line 1, in <module>
    from torchsdf.sdf import *
  File "/home/X/DOWNLOAD/TorchSDF/torchsdf/sdf.py", line 2, in <module>
    from torchsdf import _C
ImportError: cannot import name '_C' from partially initialized module 'torchsdf' (most likely due to a circular import) (/home/X/DOWNLOAD/TorchSDF/torchsdf/__init__.py)`

**Comment by ZZQ0316** [comment]
Hi, did you solve this problem?

**Comment by meghbhalerao** [comment]
I am getting the same error. @zhengbi-yong did you find a solution for this? thanks!
